### ISSUE TITLE
Áttu tilbúna útgáfu af þessu?

### ISSUE THREAD

**Issue by baldurh** [tryggvil/RUV.bundle#1]
Væri mjög svo til í að prófa þetta ef þú kláraðir þetta einhvern tíma :)

**Comment by tryggvil** [comment]
Nei ég hef ekki snert þetta í dágóðan tíma. Scraping lógíkin er líklega orðin úreld vegna þess að það er kominn nýr ruv.is . Hefur langað til að útfæra þetta með apis.is , http://docs.apis.is/#endpoint-tv sem væri nice ef þeir hafa allar upplýsingar.
